# Generated by Django 4.2.5 on 2024-01-14 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="filmwork",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="genrefilmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="personfilmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="filmwork",
            name="file_path",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="File path"
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="rating",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="rating",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.TextField(
                choices=[
                    ("actor", "actor"),
                    ("director", "Director"),
                    ("writer", "Writer"),
                ],
                default="actor",
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
